### ISSUE TITLE
Crash on hitting play button

### ISSUE THREAD

**Issue by dmarcuse** [viluon/CCJam-2016#7]
After hitting play and then setting my username and hitting play again:

![Screenshot](https://i.imgur.com/HvlREed.png)

**Comment by viluon** [comment]
This is a known issue, the game is trying to send data over rednet when no modems are present. This is fixed in both [`after-jam`](https://github.com/viluon/CCJam-2016/tree/after-jam) and [`release`](https://github.com/viluon/CCJam-2016/tree/release) branches, but if you want to stick to the original version, attaching a wireless modem to your computer should fix the issue.

**Comment by dmarcuse** [comment]
Alright, I thought I had a modem attached but I'll try again.
